### ISSUE TITLE
Store jenkins configuration into this repo

### ISSUE THREAD

**Issue by sboeuf** [clearcontainers/jenkins#2]
We need to store all our Jenkins configuration into this repo so that we don't loose all our precious configs.

**Comment by sboeuf** [comment]
Created because of the conversation on https://github.com/clearcontainers/tests/issues/540

**Comment by jodh-intel** [comment]
As discussed, we'll also need a README explaining:

- What this repo is for.
- How to use the config data it contains:
  - Ideally, how to set up a new node using it and/or handle DR recovery in case of system failure.

**Comment by jodh-intel** [comment]
As the 16.04 setup is currently broken, we also need to migrate goveralls to the 17.04 config as we currently have no unit-test coverage check.
