### ISSUE TITLE
Fix Fedora 26 Jenkins nodes

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/jenkins#32]
The Fedora 26 Jenkins nodes (atleast for `runtime` and `tests`) seem to be broken. Every new PR is failing on F26 with errors such as:

- openshift test failure.
- Jenkins exceptions.
- missing `git` command.

Example affected PRs:

- https://github.com/clearcontainers/tests/pull/807
- https://github.com/clearcontainers/tests/pull/816
- https://github.com/clearcontainers/runtime/pull/887
- https://github.com/clearcontainers/runtime/pull/884
- https://github.com/clearcontainers/runtime/pull/863

**Comment by chavafg** [comment]
After digging into the Fedora failures, `cc-runtime list` seems to be the problem: https://github.com/clearcontainers/runtime/issues/902

`git` is installed after the VM is launched.
Still need to take a look at the jenkins exceptions.

**Comment by chavafg** [comment]
A quick 'nasty' fix for the CI would be to comment this line: 
https://github.com/clearcontainers/tests/blob/master/integration/openshift/hello_world.bats#L47 

And uncomment it once https://github.com/clearcontainers/runtime/issues/902 is fixed.

**Comment by chavafg** [comment]
So this is was fixed with https://github.com/clearcontainers/tests/pull/833. Closing issue... Still  https://github.com/clearcontainers/runtime/issues/902 need to be investigated furtherly
