### ISSUE TITLE
Jenkins claims no kvm kernel module and fails build

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/jenkins#4]
```
08:17:02 ERROR: kernel module "kvm" (Kernel-based Virtual Machine) not found
08:17:02 Build step 'Execute shell' marked build as failure
```

From:

- http://cc-jenkins-ci.westus2.cloudapp.azure.com/job/clear-containers-runtime-azure-ubuntu-16-04/153/consoleText

**Comment by sboeuf** [comment]
We have just figured that something changed inside the Ubuntu 16.04 LTS image provided by Azure. A custom kernel 4.11 has not CONFIG_KVM enabled, meaning there is no kvm support on this image. This is under investigation, we are gonna reach out the folks from Microsoft about that.

**Comment by sboeuf** [comment]
Issue is taken care of by Canonical team and tracked here: https://bugs.launchpad.net/ubuntu/+source/linux-azure/+bug/1718740
New image should be out in a week.

**Comment by grahamwhaley** [comment]
Excellent - thanks @sboeuf

**Comment by sboeuf** [comment]
Solved by uploading a good Ubuntu image to our Azure storage account, making Jenkins relying on it. I would keep this issue opened since there is still a fix for the Ubuntu image on Azure marketplace in the pipe.

**Comment by jodh-intel** [comment]
Closing as this problem was resolved months ago...
